### ISSUE TITLE
Project homepage redirects to random third-party site

### ISSUE THREAD

**Issue by ypcs** [avoindata/meta#1]
Currently this project has http://datajournalismi.fi/ configured as homepage. However, that site seems to redirect to tallinnanmatka.fi.

```
$ curl -ILsS https://datajournalismi.fi/
HTTP/2 301
date: Mon, 25 Feb 2019 08:05:45 GMT
server: Apache
location: http://www.laivallatallinnaan.fi/
content-type: text/html; charset=iso-8859-1

HTTP/1.1 301 Moved Permanently
Date: Mon, 25 Feb 2019 08:05:45 GMT
Server: Apache
Location: http://www.tallinnanmatka.fi/
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 301 Moved Permanently
Date: Mon, 25 Feb 2019 08:05:45 GMT
Server: Apache
Upgrade: h2,h2c
Connection: Upgrade
Location: https://www.tallinnanmatka.fi/
Content-Type: text/html; charset=UTF-8

HTTP/2 200
date: Mon, 25 Feb 2019 08:05:45 GMT
server: Apache
link: <https://www.tallinnanmatka.fi/wp-json/>; rel="https://api.w.org/", <https://www.tallinnanmatka.fi/>; rel=shortlink
content-type: text/html; charset=UTF-8
```

**Comment by ypcs** [comment]
Assigned issue to all owners of the project, I have no idea who has managed that site previously.

**Comment by d2s** [comment]
Removed the old URL from _Organization profile_ settings.

## Before

<img width="361" alt="2019-02-24-github-avoindata-settings-before" src="https://user-images.githubusercontent.com/135053/53343462-1a511d80-3919-11e9-8863-915e8de86187.PNG">

## After

<img width="353" alt="2019-02-24-github-avoindata-settings-after" src="https://user-images.githubusercontent.com/135053/53343485-250bb280-3919-11e9-9cc1-5dd1ae91e3d4.PNG">


## What to do in the future?

No idea who had managed that site, or what to do with it.
But at least the GitHub organization's profile does not point to that URL anymore.
